# Header
logo: "/static/images/SYNAPTIC-RESEARCH-GROUP.jpg2.jpg"
cta:
  enable: true
  text: "Get Started"
  link: "/converting-data-to-nwb/"

# Footer
footer_logo: "/images/colored-logo.png"
copyright_text: "© Neurodata Without Borders - All Rights Reserved"
